# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hookah Manager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'MMDrawerController', '~> 0.5.7'
pod 'NYAlertViewController', '~> 1.3'
pod "AFNetworking", "~> 2.0"
pod 'SDWebImage', '~>3.7'
pod 'Realm', '~> 2.1'
source 'https://github.com/CocoaPods/Specs.git'
pod 'GoogleMaps'

  # Pods for Hookah Manager

end
