# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Verifier_new' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Verifier_new
	pod 'Alamofire', '~> 4.7'
	pod 'IQKeyboardManagerSwift'
	pod 'Cosmos'
	pod 'MBProgressHUD'
	pod 'SDWebImage'
	pod 'Firebase/Core'
  	pod 'Firebase/Messaging'

    	pod 'FacebookCore'
    	pod 'FacebookLogin'
    	pod 'FacebookShare'
	pod 'SwiftyVK'
	pod 'ImageSlideshow', '~> 1.6'
	pod 'PopupDialog', '~> 0.9'
	pod 'UIColor_Hex_Swift', '~> 4.2.0'
	pod 'UDatePicker', '~> 1.1.0'
	pod 'RealmSwift'
	pod 'SwiftPullToRefresh'
	pod "JMMaskTextField-Swift"
	pod 'EmptyDataSet-Swift', '~> 4.0.5'
	pod 'Mapbox-iOS-SDK', '~> 4.7'
	pod "ReverseExtension"
	pod 'GoogleMaps'
  	pod 'GooglePlaces'
  	pod 'GooglePlacePicker'
	pod 'TTSegmentedControl'
	pod 'BadgeSwift', '~> 7.0'
	pod 'DropDown'
	pod 'StepSlider'
	pod 'UICircularProgressRing'

end
