# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Verifier' do
  use_frameworks!
  
  
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'Cosmos'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'MBProgressHUD'
  pod 'R.swift'
  pod 'SDWebImage', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'YouTubePlayer'
  pod 'PopupDialog', '~> 0.5.4'

end
